# inherit_from: ../.rubocop.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 50
